version: "3.9"
services:
  alpine:
    build:
      context: ./alpine
      dockerfile: Dockerfile
    image: custom-alpine
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DATABASE: "mydb"  
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: "mydb"
      MYSQL_HOST: "mysql-container"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  dbData:
