version: "3.9"
services:
  php-apache:
    ports:
      - "80:80" #The default http port
    build: './build/php'  #here is the dockerfile
    volumes:
      - ./app:/var/www/html #all the stuff will go here, the root of the Apache server
  mysql:
    ports:
      - "3306:3306" #it is actually the default port for the mysql, therefore it will be directly accessible from localhost
    build: './build/mysql'  #the build: defines the whole build process
    environment:  #environment variables
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "test_database"  #the default database, it is created if not present
      MYSQL_HOST: "mysql"
      MYSQL_USER: "testUser"
      MYSQL_PASSWORD: "testPassword1234"
    volumes:
      - dbData:/var/lib/mysql #this is for the data to be persistent if the container is shut down
volumes:
  app:
  dbData: